name: Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-20.04
    env:
      VITE_PERSONAL_ACCESS_TOKEN: ${{ secrets.VITE_PERSONAL_ACCESS_TOKEN }}
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
      VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
      VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
      VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
      VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
      VITE_USER_ID: ${{ secrets.VITE_USER_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: npm run build --if-present        
        env:
          CI: false
      - name: Copy folder content recursively to VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /home/dinujaya/web/dinujaya.me/public_html
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
      - run: echo "Deployment status is ${{ job.status }}."
